- !<LabBrick>
  id: 25331
  name: LB_QUBIT
  frequency: 5.0E+9
  power: 13.0
- !<LabBrick>
  id: 25335
  name: LB_RR
  frequency: 5.0E+9
  power: 13.0
- !<Sa124>
  id: 19184645
  name: SA
  center: 5.0E+9
  span: 1.0E+8
  rbw: 2.5E+5
  ref_power: 0.0
