- !<Qubit>
  name: qubit
  lo: 25331
  int_freq: -5.000000E+07
  ports:
    I: 1
    Q: 2
  mixer_offsets:
    I: 0.0069958885549567616
    Q: -0.006654385034926237
    G: -0.1877040624851362
    P: 0.09362514408421704
  operations:
    constant_pulse: !<ConstantPulse>
      length: 20
      ampx: 1.0
    gaussian_pulse: !<GaussianPulse>
      sigma: 4
      chop: 4
      ampx: 1.5
      drag: 0.0
- !<Readout>
  name: rr
  lo: 25335
  int_freq: -5.000000E+07
  ports:
    I: 4
    Q: 3
    out: 1
  mixer_offsets:
    I: -0.018960010539740325
    Q: 0.0016848570201545951
    G: 0.166064453125
    P: -0.14304199218750002
    out: 0.0
  operations:
    constant_pulse: !<ConstantPulse>
      length: 1000
      ampx: 1.0
    gaussian_pulse: !<GaussianPulse>
      sigma: 6
      chop: 6
      ampx: 1.0
      drag: 0.0
    readout_pulse: !<ConstantPulse>
      length: 1000
      ampx: 1.0
      integration_weights: !<ConstantPulse>
        length: 250
        ampx: 5.0
  time_of_flight: 180
  smearing: 0
