- !<Qubit>
  name: QUBIT
  lo: LB_QUBIT
  int_freq: -5.000000E+07
  ports:
    I: 1
    Q: 2
  mixer_offsets:
    I: 0.0073768358677625614
    Q: -0.006263349205255512
    G: -0.1866107218898833
    P: 0.09363464538473644
  operations:
    constant_pulse: !<ConstantPulse>
      length: 20
      ampx: 1.0
    gaussian_pulse: !<GaussianPulse>
      sigma: 4
      chop: 4
      ampx: 1.5
      drag: 0.0
- !<Readout>
  name: RR
  lo: LB_RR
  int_freq: -5.000000E+07
  ports:
    I: 4
    Q: 3
    out: 1
  mixer_offsets:
    I: -0.018277904391288752
    Q: 0.0013034597039222715
    G: 0.16446459293365484
    P: -0.1454572081565857
    out: 0.0
  operations:
    constant_pulse: !<ConstantPulse>
      length: 1000
      ampx: 1.0
    gaussian_pulse: !<GaussianPulse>
      sigma: 6
      chop: 6
      ampx: 1.0
      drag: 0.0
    readout_pulse: !<ConstantPulse>
      length: 1000
      ampx: 1.0
      integration_weights: !<ConstantPulse>
        length: 250
        ampx: 5.0
  time_of_flight: 180
  smearing: 0
