- !<Qubit>
  name: QUBIT
  lo: LB_QUBIT
  int_freq: -1.000000E+08
  ports:
    I: 1
    Q: 2
  mixer_offsets:
    I: 0.0032896532648010197
    Q: -0.006378329504514115
    G: -0.16863422393798827
    P: 0.10583176612854006
  operations:
    constant_pulse: !<ConstantPulse>
      length: 20
      ampx: 1.0
    gaussian_pulse: !<GaussianPulse>
      sigma: 4
      chop: 4
      ampx: 1.5
      drag: 0.0
- !<Readout>
  name: RR
  lo: LB_RR
  int_freq: -1.000000E+07
  ports:
    I: 4
    Q: 3
    out: 1
  mixer_offsets:
    I: -0.02861595079302788
    Q: 0.0031809721142053646
    G: 0.15357230007648467
    P: -0.052300423383712775
    out: 0.0
  operations:
    constant_pulse: !<ConstantPulse>
      length: 1000
      ampx: 1.0
    gaussian_pulse: !<GaussianPulse>
      sigma: 6
      chop: 6
      ampx: 1.0
      drag: 0.0
    readout_pulse: !<ConstantPulse>
      length: 1000
      ampx: 1.0
      integration_weights: !<ConstantPulse>
        length: 250
        ampx: 5.0
  time_of_flight: 180
  smearing: 0
